import Link from "next/link";
import type { BlogPost } from "@/lib/blog-posts";

export function ArticleBody({ post, relatedPosts }: { post: BlogPost; relatedPosts: BlogPost[] }) {
  return <>
    <div className="rounded-2xl border border-gold/25 bg-gold/5 p-5"><p className="text-xs uppercase tracking-[.18em] text-gold">Quick answer</p><p className="mt-3 text-sm leading-relaxed text-cream">{post.sections[0]?.paragraphs[0]}</p></div>
    <div className="mt-10 space-y-10">{post.sections.map((section, sectionIndex) => <section key={section.heading}><h2 className="font-display text-2xl text-cream">{section.heading}</h2>{section.paragraphs.filter((_, paragraphIndex) => !(sectionIndex === 0 && paragraphIndex === 0)).map((paragraph) => <p key={paragraph} className="mt-4 text-sm leading-7 text-lav">{paragraph}</p>)}{section.bullets && <ul className="mt-4 space-y-2 text-sm leading-relaxed text-lav">{section.bullets.map((bullet) => <li key={bullet} className="rounded-xl border border-gold/10 bg-white/[.025] p-3">{bullet}</li>)}</ul>}{section.table && <div className="mt-5 overflow-x-auto rounded-2xl border border-gold/15"><table className="min-w-full text-left text-sm"><tbody>{section.table.map((row, index) => <tr key={`${section.heading}-${index}`} className="border-b border-white/10 last:border-0">{row.map((cell, cellIndex) => index === 0 ? <th key={cell} className="min-w-40 bg-gold/5 px-4 py-3 font-medium text-cream">{cell}</th> : <td key={`${cell}-${cellIndex}`} className="min-w-40 px-4 py-3 text-lav">{cell}</td>)}</tr>)}</tbody></table></div>}</section>)}</div>
    <div className="mt-12 rounded-2xl border border-gold/30 bg-gradient-to-br from-gold/10 to-transparent p-6"><p className="text-xs uppercase tracking-[.18em] text-gold">Next step</p><h2 className="mt-2 font-display text-2xl text-cream">{post.cta.label}</h2><p className="mt-3 text-sm leading-relaxed text-lav">{post.cta.description}</p><Link href={post.cta.href} className="mt-5 inline-flex min-h-11 items-center justify-center rounded-full bg-gold px-5 py-3 text-sm font-semibold text-midnight hover:bg-goldlite">Open Magic of Numbers</Link></div>
    <section className="mt-12"><h2 className="font-display text-2xl text-cream">Frequently asked questions</h2><div className="mt-5 space-y-3">{post.faq.map((item) => <details key={item.question} className="rounded-xl border border-gold/15 bg-[#101225]/60 p-4"><summary className="cursor-pointer text-sm font-medium text-cream">{item.question}</summary><p className="mt-3 text-sm leading-relaxed text-lav">{item.answer}</p></details>)}</div></section>
    <section className="mt-12"><h2 className="font-display text-2xl text-cream">Related guides</h2><div className="mt-5 grid gap-3 sm:grid-cols-3">{relatedPosts.map((related) => <Link key={related.slug} href={`/blog/${related.slug}`} className="rounded-xl border border-gold/15 p-4 text-sm text-lav transition hover:border-gold/40 hover:text-cream">{related.title}</Link>)}</div></section>
  </>;
}
